/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

import '@/global.css';

import { Platform } from 'react-native';

export const Colors = {
  light: {
    text: '#000000',
    textSecondary: '#60646C',
    textMuted: '#808794',
    textTitle: '#0F1729',
    background: '#ffffff',
    backgroundSecondary: '#F4F4F7',
    backgroundElement: '#F0F0F3',
    backgroundSelected: '#E0E1E6',
    cardBackground: '#FFFFFF',
    cardBackgroundSubtle: '#F8F9FA',
    cardPressed: '#F5F5F7',
    border: '#E3E8F0',
    borderSubtle: '#EDF0F5',
    divider: '#EDF0F5',
    sheetBackground: '#F4F4F7',
    modalBackground: '#FFFFFF',
    composerBackground: '#FFFFFF',
    composerPlaceholder: '#999999',
    composerBorder: '#E3E8F0',
    composerSendIconInactive: '#FFFFFF',
    bubbleUser: '#F1F1F1',
    bubbleUserText: '#0D0D0D',
    bubbleAssistant: 'transparent',
    bubbleAssistantText: '#0D0D0D',
    icon: '#0F1729',
    iconMuted: '#617085',
    linkPrimary: '#007AFF',
    accentPrimary: '#007AFF',
    accentDot: '#007AFF',
    badgeBackground: '#EF4444',
    badgeText: '#FFFFFF',
    dropdownBackground: '#FFFFFF',
    dropdownBorder: '#EDF0F5',
    dropdownItemPressed: '#F5F5F7',
    glassButtonBackground: '#FFFFFF',
    glassButtonBorder: 'rgba(0, 0, 0, 0.06)',
    overlayFadeStart: '#FFFFFF',
    inputBackground: '#FFFFFF',
    inputBorder: '#E0E0E5',
    inputBorderActive: '#0D0D0D',
    inputText: '#0D0D0D',
    inputPlaceholder: '#99999E',
    buttonPrimaryBackground: '#0D0D0D',
    buttonPrimaryText: '#FFFFFF',
    buttonSecondaryBackground: '#FFFFFF',
    buttonSecondaryText: '#0D0D0D',
    buttonSecondaryBorder: '#E0E0E5',
  },
  dark: {
    text: '#ffffff',
    textSecondary: '#94A3B8',
    textMuted: '#64748B',
    textTitle: '#F8FAFC',
    background: '#000000',
    backgroundSecondary: '#121316',
    backgroundElement: '#1E2025',
    backgroundSelected: '#2A2D35',
    cardBackground: '#18191D',
    cardBackgroundSubtle: '#1E2026',
    cardPressed: '#25272E',
    border: '#2A2D35',
    borderSubtle: '#1E2026',
    divider: '#22252C',
    sheetBackground: '#121316',
    modalBackground: '#1A1B20',
    composerBackground: '#1E2026',
    composerPlaceholder: '#64748B',
    composerBorder: '#2A2D35',
    composerSendIconInactive: '#94A3B8',
    bubbleUser: '#26282E',
    bubbleUserText: '#FFFFFF',
    bubbleAssistant: 'transparent',
    bubbleAssistantText: '#F8FAFC',
    icon: '#F8FAFC',
    iconMuted: '#94A3B8',
    linkPrimary: '#0A84FF',
    accentPrimary: '#0A84FF',
    accentDot: '#0A84FF',
    badgeBackground: '#EF4444',
    badgeText: '#FFFFFF',
    dropdownBackground: '#1E2026',
    dropdownBorder: '#2A2D35',
    dropdownItemPressed: '#272A32',
    glassButtonBackground: '#22252C',
    glassButtonBorder: 'rgba(255, 255, 255, 0.12)',
    overlayFadeStart: '#000000',
    inputBackground: '#1E2026',
    inputBorder: '#2A2D35',
    inputBorderActive: '#FFFFFF',
    inputText: '#FFFFFF',
    inputPlaceholder: '#64748B',
    buttonPrimaryBackground: '#FFFFFF',
    buttonPrimaryText: '#000000',
    buttonSecondaryBackground: '#262626',
    buttonSecondaryText: '#FFFFFF',
    buttonSecondaryBorder: '#3A3A3C',
  },
};

export type ThemeColor = keyof typeof Colors.light & keyof typeof Colors.dark;

export const Typography = {
  caption2: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '400',
  },
  caption1: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '400',
  },
  footnote: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
  },
  subheadline: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  body: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
  },
  bodyMedium: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
  },
  title3: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '600',
  },
  title2: {
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '700',
  },
  title1: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '700',
  },
  largeTitle: {
    fontSize: 34,
    lineHeight: 41,
    fontWeight: '700',
  },
} as const;

export type TypographyVariant = keyof typeof Typography;

export const FontSizes = {
  xxs: 11,
  xs: 12,
  sm: 14,
  base: 16,
  lg: 18,
  xl: 20,
  '2xl': 24,
  '3xl': 30,
  '4xl': 36,
  '5xl': 48,
} as const;

export type FontSize = keyof typeof FontSizes;

export const LineHeights = {
  xxs: 14,
  xs: 16,
  sm: 20,
  base: 24,
  lg: 26,
  xl: 28,
  '2xl': 32,
  '3xl': 38,
  '4xl': 44,
  '5xl': 52,
} as const;

export type LineHeight = keyof typeof LineHeights;

export const FontWeights = {
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
} as const;

export type FontWeight = keyof typeof FontWeights;

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: 'var(--font-display)',
    serif: 'var(--font-serif)',
    rounded: 'var(--font-rounded)',
    mono: 'var(--font-mono)',
  },
});

export const Spacing = {
  half: 2,
  one: 4,
  two: 8,
  three: 16,
  four: 24,
  five: 32,
  six: 64,
} as const;

export const BottomTabInset = Platform.select({ ios: 50, android: 80 }) ?? 0;
export const MaxContentWidth = 800;

export const SplashTokens = {
  colors: {
    background: '#FFFFFF',
    foreground: '#000000',
  },
  expressionSize: 64,
  signature: {
    fontSize: 14,
    lineHeight: 17,
    safeAreaGap: 16,
  },
  motion: {
    minimumVisibleDuration: 1_000,
    fadeDuration: 200,
  },
} as const;

export const WelcomeTokens = {
  colors: {
    background: '#FFFFFF',
    textPrimary: '#0D0D0D',
    textSecondary: '#666666',
    textDescription: '#66666E',
    textLegal: '#808080',
    buttonBackground: '#0D0D0D',
    buttonText: '#FFFFFF',
    iconStroke: '#4D4D4D',
    link: '#0D0D0D',
  },
  typography: {
    headerTitle: {
      fontSize: 34,
      fontWeight: '600' as const,
      lineHeight: 41,
    },
    headerSubtitle: {
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 24,
    },
    rowTitle: {
      fontSize: 16,
      fontWeight: '600' as const,
      lineHeight: 22,
    },
    rowDescription: {
      fontSize: 15,
      fontWeight: '400' as const,
      lineHeight: 22,
    },
    buttonText: {
      fontSize: 15,
      fontWeight: '600' as const,
      lineHeight: 20,
    },
    legalText: {
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
  },
  spacing: {
    horizontalPadding: 24,
    contentGap: 32,
    headerGap: 12,
    infoContainerGap: 24,
    infoRowGap: 16,
    iconSize: 24,
    textGap: 4,
    actionsGap: 16,
    buttonHeight: 52,
    buttonRadius: 999,
  },
} as const;

export const AuthTokens = {
  colors: {
    light: {
      background: '#FFFFFF',
      textPrimary: '#0D0D0D',
      sheetBackground: '#000000',
      appleButtonBackground: '#FFFFFF',
      appleButtonText: '#000000',
      googleButtonBackground: '#FFFFFF',
      googleButtonText: '#0D0D0D',
      loginButtonBackground: '#262626',
      loginButtonText: '#FFFFFF',
      dotColor: '#0D0D0D',
    },
    dark: {
      background: '#000000',
      textPrimary: '#FFFFFF',
      sheetBackground: '#121316',
      appleButtonBackground: '#FFFFFF',
      appleButtonText: '#000000',
      googleButtonBackground: '#FFFFFF',
      googleButtonText: '#0D0D0D',
      loginButtonBackground: '#262626',
      loginButtonText: '#FFFFFF',
      dotColor: '#FFFFFF',
    },
    background: '#FFFFFF',
    textPrimary: '#0D0D0D',
    sheetBackground: '#000000',
    appleButtonBackground: '#FFFFFF',
    appleButtonText: '#000000',
    googleButtonBackground: '#FFFFFF',
    googleButtonText: '#0D0D0D',
    loginButtonBackground: '#262626',
    loginButtonText: '#FFFFFF',
    dotColor: '#0D0D0D',
    // Login or Sign Up Sheet (White Sheet)
    emailSheetBackground: '#FFFFFF',
    emailSheetHandle: '#D1D1D6',
    emailSheetTitle: '#0D0D0D',
    emailSheetSubtitle: '#73737A',
    emailInputBackground: '#FFFFFF',
    emailInputBorder: '#E0E0E5',
    emailInputBorderActive: '#0D0D0D',
   emailInputText: '#0D0D0D',
   emailInputLabel: '#8C8C94',
   emailInputPlaceholder: '#99999E',
   emailErrorText: '#52525B',
   emailErrorIcon: '#52525B',
   inputErrorBorder: '#E53935',
   continueButtonBackground: '#0D0D0D',
   continueButtonText: '#FFFFFF',
    dividerLine: '#E5E5EB',
    dividerText: '#99999E',
    ssoButtonBackground: '#FFFFFF',
    ssoButtonBorder: '#E0E0E5',
    ssoButtonText: '#0D0D0D',
    forgotPasswordText: '#66666E',
    legalFooterText: '#8C8C94',
  },
  typography: {
    headerTitle: {
      fontSize: 38,
      fontWeight: '700' as const,
      lineHeight: 46,
      letterSpacing: -1,
    },
    sheetTitle: {
      fontSize: 22,
      fontWeight: '400' as const,
      lineHeight: 28,
    },
    sheetSubtitle: {
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
    buttonText: {
      fontSize: 15,
      fontWeight: '600' as const,
      lineHeight: 20,
    },
    ssoButtonText: {
      fontSize: 15,
      fontWeight: '500' as const,
      lineHeight: 20,
    },
    inputLabel: {
      fontSize: 11,
      fontWeight: '400' as const,
      lineHeight: 14,
    },
    inputText: {
      fontSize: 15,
      fontWeight: '400' as const,
      lineHeight: 21,
    },
    errorText: {
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
    dividerText: {
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
  },
  spacing: {
    sheetRadius: 28,
    sheetPaddingTop: 16,
    sheetPaddingBottom: 34,
    sheetPaddingHorizontal: 24,
    sheetGap: 16,
    buttonHeight: 52,
    buttonRadius: 999,
    buttonGap: 10,
    dotSize: 26,
    headerGap: 6,
    inputGap: 8,
    formGap: 16,
    handleWidth: 36,
    handleHeight: 5,
    handleRadius: 2.5,
  },
} as const;

export const SidebarTokens = {
  width: 300,
  paddingHorizontal: 20,
  openMs: 250,
  closeMs: 200,
  surfaceRadius: 44,
  zIndex: {
    drawer: 1,
    surface: 30,
    overlay: 40,
  },
  safeArea: {
    minTop: 20,
    minBottom: 34,
  },
  colors: {
    light: {
      background: '#FFFFFF',
      surface: '#FFFFFF',
      title: '#0F0F0F',
      nav: '#1F1F1F',
      section: '#262626',
      recent: '#212121',
      chatButtonText: '#FFFFFF',
    },
    dark: {
      background: '#000000',
      surface: '#18191D',
      title: '#FFFFFF',
      nav: '#FFFFFF',
      section: '#94A3B8',
      recent: '#FFFFFF',
      chatButtonText: '#FFFFFF',
    },
  },
  surfaceShadow: {
    light: {
      shadowColor: '#000000',
      shadowOffset: { width: -12, height: 0 },
      shadowOpacity: 0.16,
      shadowRadius: 24,
      elevation: 12,
    },
    dark: {
      shadowColor: '#000000',
      shadowOffset: { width: -12, height: 0 },
      shadowOpacity: 0.45,
      shadowRadius: 24,
      elevation: 12,
    },
  },
  header: {
    height: 56,
    marginBottom: 14,
    titleFontSize: 20,
    titleFontWeight: '700' as const,
  },
  searchButton: {
    size: 40,
    radius: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  nav: {
    gap: 16,
    itemGap: 14,
    marginBottom: 28,
    fontSize: 15,
    fontWeight: '600' as const,
  },
  section: {
    fontSize: 13,
    fontWeight: '700' as const,
    marginBottom: 12,
  },
  pinned: {
    itemGap: 12,
    marginBottom: 22,
    fontSize: 14,
    fontWeight: '500' as const,
  },
  recents: {
    gap: 16,
    fontSize: 14,
    fontWeight: '500' as const,
  },
  bottomBar: {
    paddingTop: 16,
  },
  chatButton: {
    width: 106,
    height: 40,
    radius: 20,
    gap: 8,
    background: '#007AFF',
    backgroundPressed: '#0056B3',
    fontSize: 15,
    fontWeight: '700' as const,
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 4,
  },
  settingsButton: {
    size: 40,
    radius: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 5,
    elevation: 4,
  },
  iconSize: {
    nav: 20,
    chat: 16,
    settings: 20,
  },
} as const;

export const ChatTokens = {
  composer: {
    background: '#FFFFFF',
    placeholder: '#999999',
    text: '#0D0D0D',
    sendButtonBackground: '#D9DEE5',
    sendButtonBackgroundActive: '#007AFF',
    sendButtonIcon: '#FFFFFF',
    borderRadius: 26,
    sendButtonRadius: 18,
    sendButtonSize: 36,
    iconSize: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 5,
    elevation: 4,
  },
  thinking: {
    label: 'Joy is thinking…',
    stages: [
      'Joy is thinking…',
      'Connecting thoughts…',
      'Formulating response…',
    ],
    stageInterval: 2800,
    fadeDuration: 220,
    labelColor: '#60646C',
    labelFontSize: 14,
    labelLineHeight: 20,
    gap: 8,
    dotsGap: 6,
    dotSize: 6,
    dotColor: '#8A8F98',
    pulseDuration: 320,
    staggerDelay: 160,
  },
  promptItem: {
    text: '#4D4D4D',
    iconSize: 20,
    gap: 12,
    paddingVertical: 10,
    fontSize: 15,
    lineHeight: 20,
  },
} as const;

export const ChatSearchTokens = {
  colors: {
    background: '#FFFFFF',
    textPrimary: '#0D0D0D',
    textSecondary: '#66666E',
    textMuted: '#8C8C94',
    textHighlight: '#0D0D0D',
    pillBackground: '#F2F2F2',
    skeleton: '#E8E8ED',
    iconTileBackground: '#FFFFFF',
    iconTileBorder: '#E5E5EB',
    resultIconBackground: '#F0F0F3',
    ctaBackground: '#0D0D0D',
    ctaText: '#FFFFFF',
    emptyIcon: '#C7C7CC',
  },
  spacing: {
    paddingHorizontal: 20,
    listGap: 16,
    sectionTop: 16,
    bottomBarGap: 10,
    bottomBarPadding: 12,
    itemGap: 12,
    emptyGap: 16,
    noResultsGap: 12,
  },
  typography: {
    sectionTitle: {
      fontSize: 15,
      fontWeight: '700' as const,
      lineHeight: 20,
    },
    itemTitle: {
      fontSize: 15,
      fontWeight: '600' as const,
      lineHeight: 20,
    },
    itemSnippet: {
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
    emptyCopy: {
      fontSize: 15,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    noResultsTitle: {
      fontSize: 17,
      fontWeight: '700' as const,
      lineHeight: 22,
    },
    noResultsSubtitle: {
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    cta: {
      fontSize: 15,
      fontWeight: '600' as const,
      lineHeight: 20,
    },
    input: {
      fontSize: 15,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
  },
  sizes: {
    emptyIcon: 64,
    iconTile: 40,
    iconTileRadius: 10,
    resultIcon: 40,
    resultIconRadius: 20,
    messageIcon: 20,
    searchIcon: 20,
    bottomBarHeight: 48,
    closeButton: 48,
    skeletonTitleWidth: 140,
    skeletonSnippetWidth: '80%' as const,
    skeletonBarHeight: 12,
    ctaPaddingHorizontal: 20,
    ctaPaddingVertical: 10,
    ctaRadius: 20,
  },
  borderRadius: {
    pill: 24,
    iconTile: 10,
  },
  animation: {
    /** Slide in from right (RTL enter). */
    enterDuration: 280,
    /** Slide out to right (LTR exit). */
    exitDuration: 220,
  },
} as const;

export const HeaderTokens = {
  saveButton: {
    height: 40,
    minWidth: 72,
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 10,
    backgroundWhite: '#FFFFFF',
    textWhite: '#0F1729',
    backgroundDark: '#0D0D0D',
    textDark: '#FFFFFF',
    backgroundBlue: '#007AFF',
    textBlue: '#FFFFFF',
    pressedBlue: '#0056B3',
    fontSize: 15,
    fontWeight: '600' as const,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  actionsButton: {
    background: '#FFFFFF',
    backgroundDark: '#22252C',
    borderLight: 'rgba(0, 0, 0, 0.06)',
    borderDark: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 20,
    height: 40,
    gap: 22,
    paddingHorizontal: 16,
    iconSize: 20,
    iconColor: '#171717',
    iconColorDark: '#F8FAFC',
  },
} as const;

export const ToggleTokens = {
  layout: {
    width: 44,
    height: 26,
    borderRadius: 13,
    thumbSize: 22,
    thumbInset: 2,
    thumbTravel: 18,
  },
  colors: {
    trackOn: '#1AB870',
    trackOff: '#E2E8F0',
    trackOffLight: '#E2E8F0',
    trackOffDark: '#2A2D35',
    thumb: '#FFFFFF',
  },
  animation: {
    duration: 180,
  },
} as const;

export const BadgeTokens = {
  background: '#EF4444',
  text: '#FFFFFF',
  size: 18,
  borderRadius: 9,
  fontSize: 11,
  lineHeight: 14,
} as const;

export const TemporaryChatTokens = {
  titleColor: '#262626',
  subtitleColor: '#737373',
  gap: 8,
  titleFontSize: 22,
  titleLineHeight: 28,
  subtitleFontSize: 14,
  subtitleLineHeight: 20,
} as const;

export const UserMessageBubbleTokens = {
  background: '#F1F1F1',
  borderRadius: 18,
  paddingVertical: 10,
  paddingHorizontal: 16,
  textColor: '#171717',
  fontSize: 15,
} as const;

export const HeaderBarTokens = {
  height: 44,
  buttonSize: 40,
  buttonRadius: 20,
  buttonBackground: '#FFFFFF',
  iconColor: '#333333',
} as const;

export const QuestionCardSheetTokens = {
  background: '#FFFFFF',
  borderRadius: 24,
  paddingVertical: 16,
  paddingHorizontal: 18,
  titleColor: '#1A1A1F',
  dividerColor: '#E0E0E5',
  optionTextColor: '#1C1C1F',
  optionHeight: 42,
  inputBackground: '#F5F5F7',
  inputRadius: 19,
  inputPlaceholder: '#99999E',
  skipTextColor: '#1C1C1F',
  paginationTextColor: '#8C8C91',
} as const;

export const ScheduleEditPillTokens = {
  height: 44,
  background: '#FFFFFF',
  borderRadius: 20,
  paddingVertical: 13,
  paddingHorizontal: 18,
  gap: 4,
  blueText: '#007AFF',
  darkText: '#1C1C1F',
  dotText: '#8C8C91',
  fontSize: 15,
} as const;

export const MessageActionBarTokens = {
  height: 26,
  itemSpacing: 16,
  iconSize: 18,
  paddingVertical: 4,
  iconColor: '#737373',
  activeColor: '#007AFF',
  selectedColor: '#171717',
  strokeWidth: 1.5,
} as const;

export const PluginsTokens = {
  colors: {
    background: "#FFFFFF",
    cardBackground: "#FFFFFF",
    border: "#E5E5EB",
    divider: "#F0F0F3",
    textPrimary: "#0D0D0D",
    textSecondary: "#66666E",
    textMuted: "#8C8C94",
    textLink: "#007AFF",
    badgeGreenBackground: "#E6F4EA",
    badgeGreenText: "#137333",
    badgeTimerBackground: "#F5F5F7",
    badgeTimerText: "#66666E",
    iconWhatsApp: "#25D366",
    iconSpotify: "#1DB954",
    destructive: "#E53935",
    inputBackground: "#F5F5F7",
  },
  borderRadius: {
    card: 16,
    input: 999,
    badge: 999,
    modal: 24,
    avatar: 10,
  },
  spacing: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    cardGap: 12,
    rowGap: 8,
  },
  policyContainer: {
    width: 354,
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 12,
    lineHeight: 16,
  },
  legalDisclaimer: {
    width: 354,
    fontSize: 11,
    lineHeight: 15,
  },
  appSection: {
    width: 354,
    height: 56,
    gap: 12,
    headerFontSize: 17,
    headerLineHeight: 22,
    nameFontSize: 14,
    nameLineHeight: 18,
    iconSize: 24,
  },
  skillsSection: {
    width: 370,
    headerFontSize: 13,
    headerLineHeight: 16,
    cardRadius: 16,
    rowHeight: 50,
    rowPaddingHorizontal: 16,
    rowPaddingVertical: 16,
    rowGap: 12,
    rowFontSize: 15,
    rowLineHeight: 20,
    dividerInsetLeft: 44,
  },
  readActionsSection: {
    width: 370,
    headerFontSize: 13,
    headerLineHeight: 16,
    cardRadius: 16,
    rowHeight: 50,
    rowPaddingHorizontal: 16,
    rowFontSize: 15,
    rowLineHeight: 20,
  dividerInsetLeft: 16,
},
permissionsCard: {
  width: 370,
  height: 50,
  cardRadius: 26,
  paddingHorizontal: 16,
  labelFontSize: 15,
    labelLineHeight: 20,
    valueFontSize: 15,
    valueLineHeight: 20,
    chevronSize: 16,
    rightGap: 4,
  },
  spotifyPlayer: {
    cardRadius: 16,
    cardPadding: 16,
    coverSize: 72,
    transportIcon: 22,
    rowHeight: 56,
    rowGap: 8,
    sectionGap: 16,
    titleFontSize: 15,
    titleLineHeight: 20,
    subtitleFontSize: 13,
    subtitleLineHeight: 18,
    headerFontSize: 13,
    headerLineHeight: 16,
    indicatorIconSize: 18,
    indicatorPaddingLeft: 8,
    indicatorPaddingRight: 4,
    activeColor: '#1DB954',
  },
} as const;

export const DropdownMenuTokens = {
  width: 260,
  containerRadius: 16,
  itemHeight: 42,
  iconSize: 18,
  labelFontSize: 14,
  labelLineHeight: 20,
  paddingHorizontal: 16,
  dividerColor: '#E0E0E5',
  dividerHeight: 1,
  labelColor: '#1C1C1F',
  destructiveColor: '#E53935',
  background: '#FFFFFF',
  shadowColor: '#000000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.12,
  shadowRadius: 16,
  elevation: 28,
} as const;

export const PairingInstructionsCardTokens = {
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#E3E8F0',
    headerLabel: '#64748B',
    badgeBackground: '#F1F5F9',
    badgeBorder: '#E3E8F0',
    badgeText: '#47556A',
    stepTitle: '#334155',
    stepDescription: '#63738C',
  },
  layout: {
    width: 354,
    borderRadius: 16,
    padding: 16,
    gap: 14,
  },
  header: {
    fontSize: 11,
    fontWeight: '600' as const,
  },
  badge: {
    size: 24,
    borderRadius: 12,
    fontSize: 11,
    fontWeight: '600' as const,
  },
  row: {
    gap: 12,
  },
  stepTitle: {
    fontSize: 13,
    fontWeight: '500' as const,
  },
  stepDescription: {
    fontSize: 12,
    fontWeight: '400' as const,
    textGap: 2,
  },
} as const;

export const PluginUninstallModalTokens = {
  width: 260,
  height: 140,
  borderRadius: 28,
  padding: 16,
  gap: 10,
  shadowColor: '#000000',
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.14,
  shadowRadius: 24,
  elevation: 8,
  colors: {
    background: '#FFFFFF',
    titleText: '#0F1729',
    descriptionText: '#596173',
    buttonBackground: '#F0F0F5',
    buttonText: '#DB2626',
  },
  typography: {
    title: {
      fontSize: 16,
      fontWeight: '600' as const,
    },
    description: {
      fontSize: 12,
      fontWeight: '400' as const,
    },
    button: {
      fontSize: 14,
      fontWeight: '500' as const,
    },
  },
  button: {
    height: 37,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
} as const;

export const PairingCodeDisplayBoxTokens = {
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#E3E8F0',
    headerLabel: '#64748B',
    timerBadgeBackground: '#FCF2F2',
    timerBadgeBorder: '#FAD1D1',
    timerBadgeText: '#DB2626',
    codeBoxBackground: '#F7FAFC',
    codeBoxBorder: '#E3E8F0',
    codeText: '#0F1729',
  },
  layout: {
    width: 354,
    height: 166,
    borderRadius: 16,
    padding: 16,
    gap: 14,
  },
  header: {
    fontSize: 11,
    fontWeight: '600' as const,
    rowHeight: 24,
  },
  timerBadge: {
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 10,
    fontWeight: '600' as const,
  },
  codeBox: {
    width: 322,
    height: 54,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 26,
    fontWeight: '700' as const,
  },
} as const;

/** Screen-level tokens for WhatsApp connect / pairing flow (Figma 611:134754). */
export const WhatsAppConnectScreenTokens = {
  colors: {
    background: '#FFFFFF',
    headerTitle: '#0F1729',
    toggleLink: '#0F1729',
    primaryButton: '#0D0D0D',
    primaryButtonText: '#FFFFFF',
  },
 layout: {
   sectionWidth: 354,
   horizontalPadding: 24,
   headerHeight: 52,
   headerMarginBottom: 10,
   headerButtonSize: 40,
   contentGapPhone: 20,
   contentGapPairing: 16,
   contentGapSuccess: 18,
   floatingPaddingTop: 8,
   floatingPaddingBottomMin: 12,
   scrollBottomExtra: 80,
 },
 headerTitle: {
    fontSize: 18,
   fontWeight: '600' as const,
   paddingHorizontal: 8,
 },
  toggleLink: {
    /** Figma 611:134801 — 12/Medium, centered row with Lucide arrow. */
    fontSize: 12,
    fontWeight: '500' as const,
    pressedOpacity: 0.7,
    hitSlop: 8,
    iconSize: 12,
    gap: 4,
  },
  primaryButton: {
    height: 52,
    borderRadius: 999,
    fontSize: 14,
    fontWeight: '600' as const,
    iconSize: 14,
    gap: 8,
    pressedOpacity: 0.85,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 4,
  },
  slide: {
    duration: 280,
  },
} as const;

/** Hero copy for WhatsApp QR pairing step (Figma 611:134859). */
export const QRPairingHeroTokens = {
  layout: {
    width: 354,
    gap: 6,
  },
  colors: {
    title: '#0F1729',
    subtitle: '#63738C',
  },
  title: {
    fontSize: 16,
    fontWeight: '600' as const,
    lineHeight: 22,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: '400' as const,
    lineHeight: 18,
  },
} as const;

/** Success hero for WhatsApp connected step (Figma 611:134817). */
export const PairingSuccessHeroTokens = {
  layout: {
    width: 354,
    gap: 10,
    iconBoxSize: 56,
    iconBoxBorderRadius: 14,
    iconSize: 36,
  },
  colors: {
    background: '#FFFFFF',
    iconBoxBorder: '#E3E8F0',
    title: '#0F1729',
    description: '#596173',
    badgeBackground: '#F1F5F9',
    badgeBorder: '#E3E8F0',
    badgeText: '#18181B',
  },
  typography: {
    title: {
      fontSize: 16,
      fontWeight: '600' as const,
    },
    description: {
      fontSize: 13,
      fontWeight: '400' as const,
    },
    badge: {
      fontSize: 10,
      fontWeight: '600' as const,
    },
  },
  badge: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
} as const;

/** Capabilities list card on WhatsApp success step (Figma 611:134826). */
export const ActiveJoyCapabilitiesCardTokens = {
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#E3E8F0',
    headerLabel: '#64748B',
    badgeBackground: '#DCF8E7',
    badgeText: '#16A34A',
    itemTitle: '#334155',
    itemDescription: '#63738C',
  },
  layout: {
    width: 354,
    borderRadius: 16,
    padding: 16,
    gap: 14,
  },
  header: {
    fontSize: 11,
    fontWeight: '600' as const,
  },
  badge: {
    size: 24,
    borderRadius: 12,
    fontSize: 11,
    fontWeight: '600' as const,
  },
  row: {
    gap: 12,
  },
  itemTitle: {
    fontSize: 13,
    fontWeight: '500' as const,
  },
  itemDescription: {
    fontSize: 12,
    fontWeight: '400' as const,
    textGap: 2,
  },
} as const;

export const ConnectedSuccessHeroTokens = {
  layout: {
    width: 354,
    outerRingSize: 72,
    outerRingRadius: 36,
    innerCircleSize: 52,
    innerCircleRadius: 26,
    marginTopIcon: 16,
    gapIconToTitle: 16,
    gapTitleToSubtitle: 8,
    gapSubtitleToCard: 24,
    subtitleMaxWidth: 320,
  },
  colors: {
    outerRingBackground: 'rgba(52, 199, 89, 0.12)',
    innerCircleBackground: '#34C759',
    checkmarkColor: '#FFFFFF',
    title: '#0F1729',
    subtitle: '#64748B',
  },
  typography: {
    checkmark: {
      fontSize: 24,
      fontWeight: '700' as const,
      lineHeight: 28,
    },
    title: {
      fontSize: 22,
      fontWeight: '700' as const,
      lineHeight: 28,
    },
    subtitle: {
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
  },
} as const;

/** QR display card for WhatsApp QR pairing step (Figma 611:134862). */
export const QRCodeDisplayBoxTokens = {
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#E3E8F0',
    headerLabel: '#64748B',
    timerBadgeBackground: '#FCF2F2',
    timerBadgeBorder: '#FAD1D1',
    timerBadgeText: '#DB2626',
    expiredBadgeBackground: '#FEF2F2',
    expiredBadgeBorder: '#FECACA',
    expiredBadgeText: '#DC2626',
    qrBoxBackground: '#F7FAFC',
    qrBoxBorder: '#E3E8F0',
    qrPlaceholderFill: '#0F1729',
    qrPlaceholderInset: '#FFFFFF',
    mirrorBadgeBackground: '#F0FDF4',
    mirrorBadgeBorder: '#BBF7D0',
    mirrorBadgeText: '#15803D',
    mirrorDot: '#22C55E',
    reloadOverlayBackground: 'rgba(255, 255, 255, 0.94)',
    reloadButtonBackground: '#0F1729',
    reloadButtonText: '#FFFFFF',
    reloadHintText: '#64748B',
  },
  layout: {
    width: 354,
    height: 260,
    borderRadius: 16,
    padding: 16,
    gap: 14,
    qrSize: 180,
  },
  header: {
    fontSize: 11,
    fontWeight: '600' as const,
    letterSpacing: 0.3,
    rowHeight: 24,
  },
  mirrorBadge: {
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: '600' as const,
    letterSpacing: 0.2,
    dotSize: 6,
  },
  timerBadge: {
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 10,
    fontWeight: '600' as const,
  },
  qrBox: {
    borderRadius: 12,
    borderWidth: 1,
    finderOuterSize: 40,
    finderOuterRadius: 6,
    finderMidSize: 26,
    finderMidRadius: 4,
    finderInnerSize: 14,
    finderInnerRadius: 2,
    finderInset: 15,
    moduleSize: 10,
    moduleRadius: 2,
  },
} as const;

export const PairingCodeHeroTokens = {
  layout: {
    width: 354,
    gap: 6,
  },
  title: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#0F1729',
  },
  subtitle: {
    fontSize: 13,
    fontWeight: '400' as const,
    color: '#596173',
    minHeight: 36,
  },
} as const;

export const PairingPhoneHeroTokens = {
  layout: {
    width: 354,
    gap: 12,
  },
  logoBox: {
    size: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E3E8F0',
    logoSize: 36,
  },
  title: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#0F1729',
  },
  subtitle: {
    fontSize: 13,
    fontWeight: '400' as const,
    color: '#596173',
  },
} as const;

export const ScheduleTokens = {
  colors: {
    background: "#FFFFFF",
    border: "#E5E5EA",
    suggestionBorder: "#E0E5EB",
    divider: "#EBECEF",
    textPrimary: "#1F1F24",
    textSecondary: "#66666E",
    textMuted: "#8E8E93",
    blueAccent: "#007AFF",
    pausedTag: "#8E8E93",
    completedTag: "#6E6E73",
    fieldBackground: "#FFFFFF",
    overlay: "rgba(0,0,0,0.25)",
    filterButtonBackground: "#FFFFFF",
    filterIconDefault: "#0D0D0D",
    filterIconActive: "#FFFFFF",
  },
  borderRadius: {
    card: 16,
    suggestionCard: 16,
    field: 12,
    button: 20,
    checkmark: 10,
    circle: 17,
    filterButton: 20,
  },
  sizes: {
    filterButton: 40,
    filterActiveInner: 34,
    filterIcon: 20,
  },
} as const;

export const SettingsTokens = {
  occupationCard: {
    width: 370,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#E5E5EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 14,
    placeholderColor: '#8F8F94',
    textColor: '#0D0D0D',
    fontSize: 15,
    lineHeight: 20,
  },
  chatgptSection: {
    width: 370,
    gap: 6,
    headerFontSize: 13,
    headerLineHeight: 16,
    headerColor: '#617085',
    headerPaddingLeft: 8,
    cardRadius: 16,
    cardBackground: '#FFFFFF',
    rowHeight: 48,
    rowPaddingHorizontal: 16,
    rowGap: 12,
    rowFontSize: 15,
    rowLineHeight: 20,
    textColor: '#0D0D0D',
    chevronSize: 16,
    iconSize: 20,
    dividerInsetLeft: 48,
    dividerColor: '#EDF0F5',
  },
  sheetLayer: {
    settings: 100,
    memory: 110,
    personalization: 120,
    about: 130,
    report: 140,
    upgrade: 150,
    nested: 160,
    modal: 200,
  },
  sheet: {
    backgroundColor: '#F4F4F7',
    borderTopRadius: 28,
    contentGap: 16,
    contentPaddingHorizontal: 16,
    contentPaddingBottom: 40,
    overlayColor: 'rgba(0,0,0,0.35)',
  },
 personalizationSheet: {
   headerTitleColor: '#0F1729',
    headerTitleFontSize: 18,
   headerPaddingBottom: 12,
   headerPaddingTop: 20,
   contentGap: 16,
   contentPaddingTop: 16,
   contentPaddingBottom: 40,
   baseCardRadius: 26,
   attributeCardRadius: 16,
   fastAnswersCardRadius: 30,
   fastAnswersCardPaddingHorizontal: 16,
   fastAnswersCardPaddingVertical: 14,
   fastAnswersSectionGap: 8,
   captionFontSize: 13,
   captionColor: '#617085',
   captionPaddingHorizontal: 8,
   sectionTitleFontSize: 13,
   sectionTitleColor: '#617085',
   sectionTitlePaddingLeft: 8,
   sectionTitleGap: 6,
   dividerColor: '#EDF0F5',
   dividerInsetHorizontal: 16,
   customInstructionsPlaceholderColor: '#8C8C94',
   cardBackground: '#FFFFFF',
   errorColor: '#C62828',
 },
 memorySheet: {
   headerTitleColor: '#0F1729',
    headerTitleFontSize: 18,
   headerPaddingBottom: 12,
   headerPaddingTop: 20,
   contentGap: 16,
   contentPaddingTop: 16,
   contentPaddingBottom: 40,
   sectionGap: 8,
   enableCardRadius: 29.5,
   enableCardPaddingHorizontal: 16,
   enableCardPaddingVertical: 14,
   summaryCardRadius: 25,
   summaryCardPaddingHorizontal: 16,
   summaryCardPaddingVertical: 14,
   summaryRowMinHeight: 50,
   labelFontSize: 15,
   labelColor: '#0D0D0D',
   captionFontSize: 13,
   captionColor: '#617085',
   captionLinkColor: '#007AFA',
   captionPaddingHorizontal: 8,
   sectionTitleFontSize: 13,
   sectionTitleColor: '#617085',
   sectionTitlePaddingLeft: 8,
   sectionTitleGap: 6,
   fieldCardRadius: 26,
   chevronSize: 20,
   chevronColor: '#0D0D0D',
   cardBackground: '#FFFFFF',
 },
 aboutSheet: {
   headerTitleColor: '#0F1729',
    headerTitleFontSize: 18,
   headerPaddingBottom: 12,
   headerPaddingTop: 20,
   contentPaddingTop: 16,
   contentPaddingBottom: 40,
   cardRadius: 26,
   cardBackground: '#FFFFFF',
   rowPaddingHorizontal: 16,
   rowPaddingVertical: 16,
   versionRowPaddingVertical: 14,
   rowGap: 12,
   labelFontSize: 15,
   labelColor: '#1A1A1A',
   versionTitleFontSize: 15,
   versionTitleColor: '#1A1A1A',
   versionSubtitleFontSize: 13,
   versionSubtitleColor: '#8C8C91',
   versionTitleSubtitleGap: 2,
   iconSize: 20,
   iconStrokeWidth: 1.5,
   iconColor: '#1A1A1A',
   dividerColor: '#E5E5EB',
   dividerInsetHorizontal: 16,
   headerButtonSize: 40,
 },
 reportAppIssueSheet: {
   headerTitleColor: '#0D0D0D',
    headerTitleFontSize: 18,
   headerPaddingBottom: 12,
    headerPaddingTop: 16,
    headerButtonSize: 40,
    contentGap: 16,
    contentPaddingTop: 16,
    contentPaddingBottom: 40,
    disclaimerFontSize: 13,
    disclaimerLineHeight: 18,
    disclaimerColor: '#6E7075',
    disclaimerLinkColor: '#007AFF',
    sendButtonHeight: 52,
    sendButtonRadius: 26,
    sendButtonFontSize: 16,
    sendButtonFontWeight: '600' as const,
    sendButtonTextColor: '#FFFFFF',
    sendButtonBackgroundEnabled: '#0D0D0D',
    sendButtonBackgroundDisabled: '#8C8C91',
    maxScreenshots: 5,
    errorColor: '#C62828',
    errorFontSize: 13,
    errorLineHeight: 18,
  },
  accountSection: {
    width: 370,
    gap: 6,
    headerFontSize: 13,
    headerLineHeight: 16,
    headerColor: '#617085',
    headerPaddingLeft: 8,
    cardRadius: 16,
    cardBackground: '#FFFFFF',
    rowHeight: 48,
    rowPaddingHorizontal: 16,
    rowGap: 12,
    rowFontSize: 15,
    rowLineHeight: 18,
    textColor: '#1A1A1A',
    valueColor: '#808794',
    upgradeColor: '#0385FA',
    iconSize: 20,
    iconStrokeWidth: 1.5,
    dividerInsetLeft: 48,
    dividerColor: '#EDF0F5',
  },
  themeSection: {
    width: 370,
    gap: 6,
    headerFontSize: 13,
    headerLineHeight: 16,
    headerColor: '#617085',
    headerPaddingLeft: 8,
    cardRadius: 16,
    cardBackground: '#FFFFFF',
    rowHeight: 48,
    rowPaddingHorizontal: 16,
    rowGap: 12,
    rowFontSize: 15,
    rowLineHeight: 18,
    textColor: '#1A1A1A',
    valueColor: '#808794',
    iconSize: 20,
    iconStrokeWidth: 1.5,
    chevronSize: 16,
    accentDotSize: 10,
    accentDotRadius: 5,
    accentDotColor: '#007AFF',
    accentRightGap: 6,
    dividerInsetLeft: 48,
    dividerColor: '#EDF0F5',
  },
  appearanceDropdown: {
    width: 170,
    topGap: 4,
    rightOffset: 16,
  },
  accentDropdown: {
    width: 170,
    topGap: 4,
    rightOffset: 16,
  },
  helpSection: {
    width: 370,
    gap: 6,
    headerFontSize: 13,
    headerLineHeight: 16,
    headerColor: '#617085',
    headerPaddingLeft: 8,
    cardRadius: 16,
    cardBackground: '#FFFFFF',
    rowHeight: 48,
    rowPaddingHorizontal: 16,
    rowGap: 12,
    rowFontSize: 15,
    rowLineHeight: 18,
    textColor: '#1A1A1A',
    iconSize: 20,
    iconStrokeWidth: 1.5,
    chevronSize: 16,
    dividerInsetLeft: 48,
    dividerColor: '#EDF0F5',
  },
  logoutCard: {
    width: 370,
    cardRadius: 16,
    cardBackground: '#FFFFFF',
    rowHeight: 48,
    rowPaddingHorizontal: 16,
    rowGap: 12,
    rowFontSize: 15,
    rowLineHeight: 18,
    textColor: '#ED4242',
    iconSize: 20,
    iconStrokeWidth: 1.5,
  },
  colors: {
    background: '#FFFFFF',
    textPrimary: '#0D0D0D',
    textSecondary: '#73737A',
    iconStroke: '#8E8E93',
  },
 styleToneRow: {
   width: 370,
   height: 50,
   paddingHorizontal: 16,
   paddingVertical: 16,
   itemSpacing: 12,
   valueSelectorGap: 4,
   labelFontSize: 15,
   valueFontSize: 15,
   iconSize: 16,
 },
  accountSecurityCard: {
    width: 370,
    cardRadius: 16,
    cardBackground: '#FFFFFF',
    rowHeight: 52,
    rowPaddingHorizontal: 16,
    rowGap: 12,
    labelFontSize: 15,
    labelLineHeight: 20,
    labelColor: '#0D0D0D',
    valueFontSize: 15,
    valueLineHeight: 20,
    valueColor: '#73737A',
    iconSize: 20,
    chevronSize: 16,
    dividerInsetLeft: 48,
    dividerColor: '#F0F0F3',
  },
 bugReportTextareaCard: {
    width: 370,
    height: 170,
    borderRadius: 20,
    backgroundColor: "#EEEEEF",
    padding: 16,
    itemSpacing: 12,
    placeholderColor: "#AEAEB5",
    textColor: "#0D0D0D",
    counterColor: "#8C8C91",
    labelColor: "#0D0D0D",
    labelFontSize: 14,
    labelLineHeight: 18,
    labelSpacing: 8,
    inputFontSize: 15,
    inputLineHeight: 20,
    counterFontSize: 13,
    counterLineHeight: 16,
    defaultMaxLength: 2000,
  },
  bugReportTogglesCard: {
    width: 370,
    height: 151,
    borderRadius: 20,
    borderRadiusCollapsed: 9999,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    rowPaddingVertical: 14,
    textColor: '#0D0D0D',
    textFontSize: 15,
    textLineHeight: 18,
    switchTrackColorOn: '#33C759',
    switchTrackColorOff: '#E9E9EA',
    uploadContainerPaddingTop: 4,
    uploadContainerPaddingBottom: 16,
    addButtonSize: 72,
    addButtonRadius: 14,
    addButtonBackground: '#F5F5F7',
    addButtonBorderColor: '#C2C2C9',
    addButtonBorderWidth: 1.5,
    plusIconSize: 22,
    plusIconColor: '#0D0D0D',
  },
  screenshotUploadContainer: {
    width: 370,
    paddingTop: 4,
    paddingBottom: 16,
    paddingHorizontal: 16,
    gap: 12,
    buttonSize: 72,
    buttonRadius: 14,
    buttonBackground: '#F5F5F7',
    buttonBorderColor: '#C2C2C9',
    buttonBorderWidth: 1.5,
    plusIconSize: 22,
    plusIconColor: '#0D0D0D',
    thumbnailSize: 72,
    thumbnailRadius: 14,
    thumbnailBackground: '#F0F2F7',
    thumbnailBorderColor: '#D9D9E0',
    thumbnailBorderWidth: 1,
    removeButtonSize: 18,
    removeButtonRadius: 99,
    removeButtonBackground: 'rgba(51, 51, 61, 0.75)',
    removeButtonTextColor: '#FFFFFF',
    removeButtonFontSize: 10,
  },
  upgradeSheet: {
    backgroundColor: '#FFFFFF',
    contentPaddingHorizontal: 24,
    contentGap: 20,
    scrollPaddingTop: 8,
    scrollPaddingBottom: 24,
  },
  upgradeProHero: {
    width: 354,
    height: 135,
    paddingTop: 8,
    paddingRight: 0,
    paddingBottom: 4,
    paddingLeft: 0,
    gap: 12,
    iconWrapperSize: 48,
    iconSize: 32,
    titleFontSize: 28,
    titleLineHeight: 33,
    titleFontWeight: '700' as const,
    titleColor: '#0D0D0D',
    subtitleFontSize: 15,
    subtitleLineHeight: 18,
    subtitleFontWeight: '400' as const,
    subtitleColor: '#5C6370',
    alignItems: 'center' as const,
    textAlign: 'center' as const,
  },
  pricingCardsRow: {
    width: 354,
    height: 84,
    gap: 12,
    cardRadius: 16,
    cardPadding: 16,
    cardGap: 2,
    colors: {
      containerBackground: '#FFFFFF',
      selectedBackground: '#EFF6FF',
      selectedBorder: '#3B82F6',
      unselectedBackground: '#FFFFFF',
      unselectedBorder: '#E2E8F0',
      titleText: '#0F172A',
      priceText: '#0F172A',
      periodText: '#64748B',
      badgeBackground: '#DBEAFE',
      badgeText: '#1D4ED8',
    },
    typography: {
      title: {
        fontSize: 15,
        fontWeight: '700' as const,
        lineHeight: 18,
      },
      price: {
        fontSize: 13,
        fontWeight: '500' as const,
        lineHeight: 16,
      },
      period: {
        fontSize: 12,
        fontWeight: '400' as const,
        lineHeight: 14,
      },
      badge: {
        fontSize: 10,
        fontWeight: '600' as const,
        lineHeight: 12,
      },
    },
  },
  upgradeProFeaturesSection: {
    width: 354,
    minHeight: 211,
    paddingTop: 4,
    gap: 12,
    listGap: 14,
    rowGap: 12,
    iconSize: 18,
    colors: {
      headerText: '#475469',
      featureText: '#0F172A',
      checkIcon: '#3B82F6',
    },
    typography: {
      header: {
        fontSize: 14,
        fontWeight: '500' as const,
        lineHeight: 18,
      },
      feature: {
        fontSize: 15,
        fontWeight: '500' as const,
        lineHeight: 20,
      },
    },
  },
  upgradeProCtaFooter: {
    width: 402,
    height: 150,
    paddingTop: 16,
    paddingBottom: 34,
    paddingHorizontal: 24,
    gap: 12,
    button: {
      height: 52,
      borderRadius: 999,
      backgroundColor: '#0D0D0D',
      textColor: '#FFFFFF',
      fontSize: 15,
      fontWeight: '600' as const,
    },
    footerCaptions: {
      gap: 4,
      fontSize: 13,
      fontWeight: '400' as const,
      autoRenewColor: '#4A5463',
      disclaimerColor: '#6B7382',
    },
  },
} as const;
export const AvatarTokens = {
  /**
   * Deterministic palette for initials avatars.
   * High contrast against light/white text with modern, balanced saturation.
   */
  palette: [
    '#475569', // Slate
    '#2563EB', // Blue
    '#059669', // Emerald
    '#D97706', // Amber
    '#DC2626', // Red
    '#7C3AED', // Violet
    '#DB2777', // Pink
    '#0891B2', // Cyan
    '#4F46E5', // Indigo
    '#EA580C', // Orange
  ] as const,
  textColor: '#FFFFFF',
  fontWeight: '600' as const,
  fallbackInitial: 'U',
} as const;


export const ProfileHeaderTokens = {
  width: 370,
  height: 108,
  gap: 8,
  avatarSize: 80,
  avatarRadius: 40,
  badgeSize: 26,
  badgeRadius: 13,
  badgeOffsetLeft: 54,
  badgeOffsetTop: 54,
  badgeBorderWidth: 1,
  badgeBorderColor: '#E5EBF0',
  badgeBackgroundColor: '#FFFFFF',
  pencilIconSize: 14,
  nameFontSize: 17,
  nameLineHeight: 22,
  nameTextColor: '#0D0D0D',
  initialsFontSize: 28,
  initialsFontWeight: '600' as const,
  initialsTextColor: '#FFFFFF',
} as const;

export const EditProfilePopupTokens = {
  /** Figma frame 611:136662 — 390×476 glass card */
  maxWidth: 390,
  height: 476,
  horizontalInset: 6,
  /** Figma parent: card sits near bottom of phone frame (y=560 on ~1077pt). */
  bottomInset: 16,
  animation: {
    enterScaleFrom: 0.9,
    enterDuration: 180,
    exitDuration: 140,
    backdropDuration: 180,
    springTension: 80,
    springFriction: 9,
  },
  borderRadius: 48,
  borderWidth: 1.5,
  paddingTop: 32.5,
  paddingBottom: 35.5,
  paddingHorizontal: 16.5,
  avatarSize: 92,
  avatarRadius: 46,
  avatarMarginBottom: 16,
  initialsFontSize: 32,
  initialsFontWeight: '600' as const,
  initialsTextColor: '#FFFFFF',
  cameraBadgeSize: 30,
  cameraBadgeRadius: 15,
  cameraBadgeBorderWidth: 1,
  cameraIconSize: 16,
  fieldWidth: 354,
  fieldHeight: 74,
  /** Figma: username top 224.5 − (name top 140.5 + 74) = 10 */
  fieldMarginBottom: 10,
  inputHeight: 52,
  inputRadius: 26,
  inputBorderWidth: 1,
  inputPaddingHorizontal: 19,
  labelMarginLeft: 14,
  labelMarginBottom: 6,
  helperWidth: 320,
  /** Figma: helper top 312.5 − (username top 224.5 + 74) = 14 */
  helperMarginTop: 14,
  /** Figma: save top 350.5 − (helper top 312.5 + 20) = 18 */
  helperMarginBottom: 18,
  /** Figma: cancel top 404.5 − (save top 350.5 + 44) = 10 */
  actionsGap: 10,
  saveButtonWidth: 136,
  saveButtonHeight: 44,
  saveButtonRadius: 22,
  cancelButtonWidth: 100,
  cancelButtonHeight: 36,
  shadow: {
    color: '#000000',
    offset: { width: 0, height: 12 },
    opacity: 0.12,
    radius: 32,
    elevation: 10,
  },
  colors: {
    background: '#FFFFFF',
    border: 'rgba(255, 255, 255, 0.95)',
    backdrop: 'rgba(0, 0, 0, 0.18)',
    label: '#6E6E73',
    inputBorder: 'rgba(204, 204, 212, 0.95)',
    inputBackground: '#FFFFFF',
    inputText: '#1A1A1A',
    placeholder: '#99999E',
    helper: '#8C8C94',
    error: '#C62828',
    saveBackground: '#000000',
    saveText: '#FFFFFF',
    cancelText: '#1A1A1A',
    cameraBadgeBackground: '#FFFFFF',
    cameraBadgeBorder: '#D9D9E0',
  },
  typography: {
    label: {
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
    input: {
      fontSize: 15,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    helper: {
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    save: {
      fontSize: 15,
      fontWeight: '600' as const,
    },
    cancel: {
      fontSize: 15,
      fontWeight: '500' as const,
    },
  },
} as const;

export const DotMatrixPatternTokens = {
  width: 370,
  height: 700,
  rows: 45,
  cols: 24,
  startX: 6.9,
  startY: 10.2,
  pitch: 15.4,
  centerX: 177.3,
  centerY: 273.0,
  sigma: 112.0,
  baseDotSize: 2.0,
  maxDotSize: 5.1867,
  baseOpacity: 0.12,
  maxOpacity: 0.55,
  dotColor: "#B2B2B8",
} as const;

export const MemorySummarySheetTokens = {
  sheetBackground: '#FFFFFF',
  borderTopRadius: 36,
  headerPaddingTop: 20,
  headerPaddingBottom: 12,
  contentPaddingHorizontal: 20,
  contentPaddingTop: 16,
  contentPaddingBottom: 120,
  sectionGap: 24,
  sectionTitleGap: 6,
  sectionTitleFont: {
    fontSize: 17,
    fontWeight: '600' as const,
    color: '#0D0D0D',
  },
  sectionBodyFont: {
    fontSize: 15,
    fontWeight: '400' as const,
    color: '#262626',
  },
  generatingDelayMs: 3000,
  pollIntervalMs: 1500,
  pollTimeoutMs: 30000,
  generatingCanvasPaddingTop: 40,
  composerOverlayPaddingHorizontal: 24,
  composerFadeHeight: 174,
  titleColumn: {
    gap: 2,
    titleFont: {
      fontSize: 17,
      fontWeight: '700' as const,
      lineHeight: 22,
      color: '#0D0D0D',
    },
    subtitleFont: {
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 18,
      color: '#8E8E93',
    },
    updatedSubtitleColor: '#737373',
  },
  moreButtonIconSize: 20,
  regenerateButtonIconSize: 20,
  actionButtonColor: '#0D0D0D',
  flashMinOpacity: 0.45,
  flashMaxOpacity: 1,
  flashDurationMs: 700,
  emptyStatePaddingTop: 48,
} as const;

export const RobotHeroCardTokens = {
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#E3E8F0',
    titleText: '#1A1A1A',
    descriptionText: '#737380',
    iconBackground: '#FFFFFF',
  },
  layout: {
    width: 362,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 12,
    innerGap: 10,
    iconBoxSize: 60,
    iconBoxRadius: 16,
    iconSize: 52,
    descriptionWidth: 320,
  },
  typography: {
    title: {
      fontSize: 18,
      fontWeight: '700' as const,
      lineHeight: 24,
    },
    description: {
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
  },
} as const;

export const RobotTokens = {
  optionCard: {
    width: 362,
    height: 68,
    borderRadius: 16,
    padding: 16,
    gap: 12,
    textGap: 4,
    leftIconSize: 20,
    chevronSize: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    colors: {
      background: '#FFFFFF',
      pressedBackground: '#F5F5F7',
      titleText: '#1A1A1A',
      descriptionText: '#737380',
      iconStroke: '#000000',
      chevronStroke: '#8E8E93',
    },
    typography: {
      title: {
        fontSize: 15,
        fontWeight: '600' as const,
        lineHeight: 18,
      },
      description: {
        fontSize: 12,
        fontWeight: '400' as const,
        lineHeight: 14,
      },
    },
  },
} as const;

export const CameraScanHeroTokens = {
  layout: {
    width: 354,
    gap: 6,
  },
  colors: {
    title: '#0F1729',
    subtitle: '#63738C',
  },
  title: {
    fontSize: 16,
    fontWeight: '600' as const,
    lineHeight: 22,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: '400' as const,
    lineHeight: 18,
  },
} as const;

export const CameraViewfinderBoxTokens = {
  width: 354,
  height: 320,
  borderRadius: 20,
  colors: {
    background: "#14171F",
    frameBorder: "#38BDA6",
    scanLine: "#1AB870",
    flashlightBackground: "rgba(255, 255, 255, 0.2)",
    flashlightBackgroundActive: "rgba(255, 255, 255, 0.4)",
  },
  frame: {
    size: 220,
    borderRadius: 16,
    borderWidth: 3,
    top: 50,
  },
  scanLine: {
    width: 200,
    height: 3,
  },
  centerIcon: {
    fontSize: 48,
  },
  flashlightButton: {
    size: 40,
    borderRadius: 20,
    iconSize: 20,
    right: 16,
    bottom: 16,
  },
} as const;

export const RobotCodeInputCardTokens = {
  colors: {
    cardBackground: "#FFFFFF",
    cardBorder: "#E3E8F0",
    cardBorderError: "#FCA5A5",
    boxBackground: "#FFFFFF",
    boxBorderInactive: "#D1D9E3",
    boxBorderActive: "#0F1729",
    boxBorderError: "#FF3B30",
    textColor: "#0F1729",
    cursorColor: "#0F1729",
  },
  layout: {
    width: 354,
    height: 92,
    paddingVertical: 20,
    borderRadius: 16,
    borderWidth: 1,
    boxGap: 8,
    boxWidth: 44,
    boxHeight: 52,
    boxBorderRadius: 12,
    boxBorderWidthInactive: 1.5,
    boxBorderWidthActive: 2,
    cursorWidth: 2,
    cursorHeight: 22,
    cursorRadius: 1,
  },
  typography: {
    digit: {
      fontSize: 22,
      fontWeight: "700" as const,
      lineHeight: 26,
    },
  },
} as const;

export const RobotDeviceStatusCardTokens = {
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#E3E8F0',
    titleText: '#0F1729',
    statusPillBackground: 'rgba(24, 24, 27, 0.08)',
    statusPillText: '#18181B',
  },
  layout: {
    width: 354,
    height: 72,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
    avatarSize: 42,
    avatarRadius: 12,
    iconSize: 40,
    statusPillHeight: 28,
    statusPillRadius: 14,
    statusPillPaddingHorizontal: 12,
  },
  typography: {
    title: {
      fontSize: 15,
      fontWeight: '600' as const,
      lineHeight: 20,
    },
    statusPill: {
      fontSize: 12,
      fontWeight: '600' as const,
      lineHeight: 16,
    },
  },
} as const;

export const ConnectedRobotHeroCardTokens = {
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#E3E8F0',
    titleText: '#0F1729',
    descriptionText: '#64748B',
    statusBadgeBackground: '#F1F5F9',
    statusBadgeBorder: '#E3E8F0',
    pulseOuterBackground: '#E3E8F0',
    pulseInnerBackground: '#18181B',
    statusText: '#18181B',
    badgeItemText: '#475569',
    dividerColor: '#E3E8F0',
    iconBackground: '#FFFFFF',
  },
  layout: {
    width: 362,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 12,
    avatarBoxSize: 64,
    avatarBoxRadius: 18,
    iconSize: 56,
    badgeRadius: 100,
    badgePaddingHorizontal: 12,
    badgePaddingVertical: 5,
    badgeGap: 8,
    pulseOuterSize: 10,
    pulseOuterRadius: 5,
    pulseInnerSize: 6,
    pulseInnerRadius: 3,
    dividerWidth: 1,
    dividerHeight: 10,
  },
  typography: {
    title: {
      fontSize: 20,
      fontWeight: '700' as const,
      lineHeight: 24,
    },
    statusText: {
      fontSize: 12,
      fontWeight: '600' as const,
      lineHeight: 16,
    },
    badgeItemText: {
      fontSize: 12,
      fontWeight: '500' as const,
      lineHeight: 16,
    },
    description: {
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
  },
} as const;

export const RobotScreenTokens = {
  colors: {
    background: '#FFFFFF',
    headerTitle: '#0F1729',
    sectionTitle: '#617085',
    toggleLink: '#0F1729',
    primaryButton: '#0F1729',
    primaryButtonText: '#FFFFFF',
    errorText: '#FF3B30',
  },
  layout: {
    sectionWidth: 362,
    pairSectionWidth: 354,
    horizontalPadding: 20,
    pairHorizontalPadding: 24,
    headerHeight: 56,
    contentGap: 16,
    sectionGap: 12,
    sectionTitlePaddingLeft: 8,
    scrollBottomExtra: 40,
    dropdownGap: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600' as const,
    lineHeight: 22,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '400' as const,
    lineHeight: 16,
  },
  toggleLink: {
    fontSize: 13,
    fontWeight: '500' as const,
    pressedOpacity: 0.7,
    hitSlop: 8,
    iconSize: 12,
    gap: 4,
  },
  primaryButton: {
    height: 52,
    borderRadius: 26,
    fontSize: 16,
    fontWeight: '600' as const,
  },
  slide: {
    duration: 280,
  },
} as const;

export const RobotDisconnectModalTokens = {
  width: 260,
  minHeight: 140,
  borderRadius: 28,
  padding: 16,
  gap: 10,
  shadowColor: '#000000',
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.14,
  shadowRadius: 24,
  elevation: 8,
  colors: {
    background: '#FFFFFF',
    titleText: '#0F1729',
    descriptionText: '#596173',
    buttonBackground: '#F0F0F5',
    buttonText: '#DB2626',
    backdrop: 'rgba(0, 0, 0, 0.4)',
  },
  typography: {
    title: {
      fontSize: 16,
      fontWeight: '600' as const,
      lineHeight: 22,
    },
    description: {
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
    button: {
      fontSize: 14,
      fontWeight: '500' as const,
    },
  },
  button: {
    height: 37,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
} as const;

export const NotificationPluginsSheetTokens = {
  colors: {
    sheetBackground: '#F4F4F7',
    headerTitle: '#0F1729',
    sectionTitle: '#737380',
    cardBackground: '#FFFFFF',
    divider: '#E5E5EB',
    rowTitle: '#0F1729',
    rowDescription: '#80808C',
    phoneBadgeBackground: '#E8F5E9',
    phoneBadgeBorder: '#C8E6C9',
    phoneBadgeText: '#1B5E20',
    actionButtonBackground: 'transparent',
    actionButtonBorder: '#0088CC',
    actionButtonText: '#0088CC',
    telegramIconBackground: '#0088CC',
    telegramLogo: '#FFFFFF',
  },
  layout: {
    contentGap: 20,
    sectionGap: 6,
    horizontalPadding: 16,
    paddingTop: 20,
    paddingBottom: 32,
    headerHeight: 40,
    headerSpacer: 4,
    pluginRowHeight: 64,
    pluginListPaddingVertical: 4,
    iconBoxSize: 40,
    iconBoxRadius: 10,
    whatsappIconBoxRadius: 14,
    telegramIconBoxRadius: 14,
    logoSize: 36,
    chevronSize: 16,
    rowGap: 12,
    textGap: 2,
    dividerInsetLeft: 68,
    badgePaddingHorizontal: 8,
    badgePaddingVertical: 2,
    badgeRadius: 6,
    actionButtonHeight: 28,
    actionButtonPaddingHorizontal: 10,
    actionButtonRadius: 14,
  },
  typography: {
    headerTitle: {
      fontSize: 18,
      fontWeight: '600' as const,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: '600' as const,
      lineHeight: 14,
    },
    rowTitle: {
      fontSize: 15,
      fontWeight: '600' as const,
      lineHeight: 18,
    },
    rowDescription: {
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
    phoneBadge: {
      fontSize: 11,
      fontWeight: '600' as const,
      lineHeight: 14,
    },
    actionButton: {
      fontSize: 11,
      fontWeight: '600' as const,
      lineHeight: 14,
    },
  },
} as const;

export const DeviceContactPickerTokens = {
  colors: {
    sheetBackground: '#F4F4F7',
    headerTitle: '#0F1729',
    sectionTitle: '#737380',
    searchBackground: '#FFFFFF',
    searchBorder: '#E3E8F0',
    searchText: '#0F1729',
    searchPlaceholder: '#80808C',
    searchIcon: '#80808C',
    cardBackground: '#FFFFFF',
    cardBorder: '#E3E8F0',
    divider: '#E5E5EB',
    nameText: '#0F1729',
    phoneText: '#80808C',
    emptyText: '#737380',
    primaryActionText: '#007AFF',
    avatarText: '#FFFFFF',
    primaryButtonBackground: '#0D0D0D',
    primaryButtonText: '#FFFFFF',
    cancelButtonText: '#60646C',
    inputBackground: '#F8F9FB',
    inputBorder: '#E3E8F0',
  },
  layout: {
    sheetRadius: 28,
    horizontalPadding: 16,
    paddingTop: 16,
    paddingBottom: 24,
    headerHeight: 40,
    searchHeight: 44,
    searchRadius: 12,
    searchPaddingHorizontal: 12,
    searchGap: 8,
    rowHeight: 56,
    rowPaddingHorizontal: 16,
    avatarSize: 36,
    avatarRadius: 18,
    cardRadius: 16,
    cardBorderWidth: 1,
    sectionGap: 6,
    sectionTitlePaddingLeft: 8,
    formCardPadding: 16,
    formCardGap: 16,
    inputGroupGap: 6,
    inputHeight: 48,
    inputRadius: 12,
    inputPaddingHorizontal: 14,
    formActionsGap: 12,
    primaryButtonHeight: 52,
    primaryButtonRadius: 26,
    cancelButtonPaddingVertical: 10,
    cancelButtonPaddingHorizontal: 16,
  },
  typography: {
    headerTitle: {
      fontSize: 18,
      fontWeight: '600' as const,
      lineHeight: 22,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: '600' as const,
      lineHeight: 14,
      letterSpacing: 0.2,
    },
    nameText: {
      fontSize: 15,
      fontWeight: '600' as const,
      lineHeight: 18,
    },
    phoneText: {
      fontSize: 13,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
    searchInput: {
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 18,
    },
    formTitle: {
      fontSize: 16,
      fontWeight: '600' as const,
      lineHeight: 20,
    },
    inputLabel: {
      fontSize: 13,
      fontWeight: '500' as const,
      lineHeight: 16,
    },
    formInput: {
      fontSize: 15,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    primaryButton: {
      fontSize: 15,
      fontWeight: '600' as const,
      lineHeight: 20,
    },
    cancelButton: {
      fontSize: 14,
      fontWeight: '500' as const,
      lineHeight: 18,
    },
  },
};

export const PluginNotificationSettingsSheetTokens = {
  colors: {
    sheetBackground: '#F4F4F7',
    sectionTitle: '#737380',
    headerTitle: '#0F1729',
    cardBackground: '#FFFFFF',
    cardBorder: '#E3E8F0',
    divider: '#E5E5EB',
    emptyTitle: '#0F1729',
    emptySubtitle: '#80808C',
    searchBackground: '#FFFFFF',
    searchBorder: '#E3E8F0',
    searchPlaceholder: '#80808C',
    accountBannerBackground: '#FFFFFF',
    accountBannerBorder: '#E3E8F0',
    accountBannerTitle: '#0F1729',
    accountBannerSubtitle: '#80808C',
    accountBadgeBackground: '#E8F5E9',
    accountBadgeBorder: '#C8E6C9',
    accountBadgeText: '#1B5E20',
    sparklesIcon: '#A855F7',
  },
  layout: {
    sheetRadius: 28,
    sectionGap: 6,
    contentGap: 16,
    sectionTitlePaddingLeft: 8,
    cardRadius: 16,
    searchHeight: 44,
    searchRadius: 12,
    accountBannerPadding: 14,
    accountBannerRadius: 16,
    accountBannerGap: 6,
    badgePaddingHorizontal: 8,
    badgePaddingVertical: 2,
    badgeRadius: 6,
  },
  typography: {
    headerTitle: {
      fontSize: 18,
      fontWeight: '700' as const,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: '600' as const,
    },
    emptyTitle: {
      fontSize: 14,
      fontWeight: '600' as const,
    },
    emptySubtitle: {
      fontSize: 12,
      fontWeight: '400' as const,
    },
    infoCaption: {
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
    accountBannerTitle: {
      fontSize: 14,
      fontWeight: '600' as const,
      lineHeight: 18,
    },
    accountBannerSubtitle: {
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
    accountBadge: {
      fontSize: 11,
      fontWeight: '600' as const,
      lineHeight: 14,
    },
  },
} as const;
